/*
 * Cleemy Expenses
 * Welcome on the documentation for the CleemyExpenses API. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developers@lucca.fr
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ExpenseTempItemMileage
 */
public class ExpenseTempItemMileageTest {
    private final ExpenseTempItemMileage model = new ExpenseTempItemMileage();

    /**
     * Model tests for ExpenseTempItemMileage
     */
    @Test
    public void testExpenseTempItemMileage() {
        // TODO: test ExpenseTempItemMileage
    }

    /**
     * Test the property 'distance'
     */
    @Test
    public void distanceTest() {
        // TODO: test distance
    }

    /**
     * Test the property 'power'
     */
    @Test
    public void powerTest() {
        // TODO: test power
    }

    /**
     * Test the property 'waypoints'
     */
    @Test
    public void waypointsTest() {
        // TODO: test waypoints
    }

}
