/*
 * Cleemy Expenses
 * Welcome on the documentation for the CleemyExpenses API. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developers@lucca.fr
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ExpenseReceipt;
import com.konfigthis.client.model.ExpenseTempItemAttendees;
import com.konfigthis.client.model.ExpenseTempItemAuthorizedActions;
import com.konfigthis.client.model.ExpenseTempItemCustomFieldsValue;
import com.konfigthis.client.model.ExpenseTempItemMileage;
import com.konfigthis.client.model.ExpenseTempItemOriginalTransaction;
import com.konfigthis.client.model.ExpenseTempItemProcessedAmounts;
import com.konfigthis.client.model.ModelEnum;
import com.konfigthis.client.model.PaymentMethodId;
import com.konfigthis.client.model.SourceId;
import com.konfigthis.client.model.StatusId;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ExpenseTempItem
 */
public class ExpenseTempItemTest {
    private final ExpenseTempItem model = new ExpenseTempItem();

    /**
     * Model tests for ExpenseTempItem
     */
    @Test
    public void testExpenseTempItem() {
        // TODO: test ExpenseTempItem
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'purchasedOn'
     */
    @Test
    public void purchasedOnTest() {
        // TODO: test purchasedOn
    }

    /**
     * Test the property 'originalTransaction'
     */
    @Test
    public void originalTransactionTest() {
        // TODO: test originalTransaction
    }

    /**
     * Test the property 'processedAmounts'
     */
    @Test
    public void processedAmountsTest() {
        // TODO: test processedAmounts
    }

    /**
     * Test the property 'expenseNatureId'
     */
    @Test
    public void expenseNatureIdTest() {
        // TODO: test expenseNatureId
    }

    /**
     * Test the property 'mileage'
     */
    @Test
    public void mileageTest() {
        // TODO: test mileage
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'effectiveQuantity'
     */
    @Test
    public void effectiveQuantityTest() {
        // TODO: test effectiveQuantity
    }

    /**
     * Test the property 'attendees'
     */
    @Test
    public void attendeesTest() {
        // TODO: test attendees
    }

    /**
     * Test the property 'axisSections'
     */
    @Test
    public void axisSectionsTest() {
        // TODO: test axisSections
    }

    /**
     * Test the property 'customFields'
     */
    @Test
    public void customFieldsTest() {
        // TODO: test customFields
    }

    /**
     * Test the property 'merchant'
     */
    @Test
    public void merchantTest() {
        // TODO: test merchant
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'expenseReceipts'
     */
    @Test
    public void expenseReceiptsTest() {
        // TODO: test expenseReceipts
    }

    /**
     * Test the property 'authorizedActions'
     */
    @Test
    public void authorizedActionsTest() {
        // TODO: test authorizedActions
    }

    /**
     * Test the property 'sourceId'
     */
    @Test
    public void sourceIdTest() {
        // TODO: test sourceId
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'ownerId'
     */
    @Test
    public void ownerIdTest() {
        // TODO: test ownerId
    }

    /**
     * Test the property 'paymentMethodId'
     */
    @Test
    public void paymentMethodIdTest() {
        // TODO: test paymentMethodId
    }

    /**
     * Test the property 'paymentMethod'
     */
    @Test
    public void paymentMethodTest() {
        // TODO: test paymentMethod
    }

    /**
     * Test the property 'statusId'
     */
    @Test
    public void statusIdTest() {
        // TODO: test statusId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
