/*
 * Cleemy Expenses
 * Welcome on the documentation for the CleemyExpenses API. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developers@lucca.fr
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Currency;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ExpenseTempItemOriginalTransaction
 */
public class ExpenseTempItemOriginalTransactionTest {
    private final ExpenseTempItemOriginalTransaction model = new ExpenseTempItemOriginalTransaction();

    /**
     * Model tests for ExpenseTempItemOriginalTransaction
     */
    @Test
    public void testExpenseTempItemOriginalTransaction() {
        // TODO: test ExpenseTempItemOriginalTransaction
    }

    /**
     * Test the property 'grossAmount'
     */
    @Test
    public void grossAmountTest() {
        // TODO: test grossAmount
    }

    /**
     * Test the property 'currencyId'
     */
    @Test
    public void currencyIdTest() {
        // TODO: test currencyId
    }

    /**
     * Test the property 'isExpenseAbroad'
     */
    @Test
    public void isExpenseAbroadTest() {
        // TODO: test isExpenseAbroad
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

}
