/*
 * Cleemy Expenses
 * Welcome on the documentation for the CleemyExpenses API. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developers@lucca.fr
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ApprovalStateId;
import com.konfigthis.client.model.ClaimStatusId;
import com.konfigthis.client.model.Currency;
import com.konfigthis.client.model.EntityBase;
import com.konfigthis.client.model.ExpenseClaimAuthorizedActions;
import com.konfigthis.client.model.ModelEnum;
import com.konfigthis.client.model.Owner;
import com.konfigthis.client.model.PaymentMethodId;
import com.konfigthis.client.model.SourceId;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ExpenseClaim
 */
public class ExpenseClaimTest {
    private final ExpenseClaim model = new ExpenseClaim();

    /**
     * Model tests for ExpenseClaim
     */
    @Test
    public void testExpenseClaim() {
        // TODO: test ExpenseClaim
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'declaredOn'
     */
    @Test
    public void declaredOnTest() {
        // TODO: test declaredOn
    }

    /**
     * Test the property 'createdOn'
     */
    @Test
    public void createdOnTest() {
        // TODO: test createdOn
    }

    /**
     * Test the property 'modifiedOn'
     */
    @Test
    public void modifiedOnTest() {
        // TODO: test modifiedOn
    }

    /**
     * Test the property 'paymentReceivedOn'
     */
    @Test
    public void paymentReceivedOnTest() {
        // TODO: test paymentReceivedOn
    }

    /**
     * Test the property 'sourceId'
     */
    @Test
    public void sourceIdTest() {
        // TODO: test sourceId
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'paymentMethodId'
     */
    @Test
    public void paymentMethodIdTest() {
        // TODO: test paymentMethodId
    }

    /**
     * Test the property 'paymentMethod'
     */
    @Test
    public void paymentMethodTest() {
        // TODO: test paymentMethod
    }

    /**
     * Test the property 'statusId'
     */
    @Test
    public void statusIdTest() {
        // TODO: test statusId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'approvalStateId'
     */
    @Test
    public void approvalStateIdTest() {
        // TODO: test approvalStateId
    }

    /**
     * Test the property 'approvalState'
     */
    @Test
    public void approvalStateTest() {
        // TODO: test approvalState
    }

    /**
     * Test the property 'authorizedActions'
     */
    @Test
    public void authorizedActionsTest() {
        // TODO: test authorizedActions
    }

    /**
     * Test the property 'ownerId'
     */
    @Test
    public void ownerIdTest() {
        // TODO: test ownerId
    }

    /**
     * Test the property 'owner'
     */
    @Test
    public void ownerTest() {
        // TODO: test owner
    }

    /**
     * Test the property 'authorId'
     */
    @Test
    public void authorIdTest() {
        // TODO: test authorId
    }

    /**
     * Test the property 'author'
     */
    @Test
    public void authorTest() {
        // TODO: test author
    }

    /**
     * Test the property 'legalEntityId'
     */
    @Test
    public void legalEntityIdTest() {
        // TODO: test legalEntityId
    }

    /**
     * Test the property 'legalEntity'
     */
    @Test
    public void legalEntityTest() {
        // TODO: test legalEntity
    }

    /**
     * Test the property 'departmentId'
     */
    @Test
    public void departmentIdTest() {
        // TODO: test departmentId
    }

    /**
     * Test the property 'department'
     */
    @Test
    public void departmentTest() {
        // TODO: test department
    }

    /**
     * Test the property 'currencyId'
     */
    @Test
    public void currencyIdTest() {
        // TODO: test currencyId
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

}
