/*
 * Cleemy Expenses
 * Welcome on the documentation for the CleemyExpenses API. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developers@lucca.fr
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ExpenseClaimsCreateNewExpenseClaimResponseDataInnerCreatedExpenseClaim;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ExpenseClaimsCreateNewExpenseClaimResponseDataInner
 */
public class ExpenseClaimsCreateNewExpenseClaimResponseDataInnerTest {
    private final ExpenseClaimsCreateNewExpenseClaimResponseDataInner model = new ExpenseClaimsCreateNewExpenseClaimResponseDataInner();

    /**
     * Model tests for ExpenseClaimsCreateNewExpenseClaimResponseDataInner
     */
    @Test
    public void testExpenseClaimsCreateNewExpenseClaimResponseDataInner() {
        // TODO: test ExpenseClaimsCreateNewExpenseClaimResponseDataInner
    }

    /**
     * Test the property 'createdExpenseClaim'
     */
    @Test
    public void createdExpenseClaimTest() {
        // TODO: test createdExpenseClaim
    }

}
