/*
 * Cleemy Expenses
 * Welcome on the documentation for the CleemyExpenses API. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developers@lucca.fr
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ExpenseTempItemProcessedAmountsVatBasesInnerCountryVatRate;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ExpenseTempItemProcessedAmountsVatBasesInner
 */
public class ExpenseTempItemProcessedAmountsVatBasesInnerTest {
    private final ExpenseTempItemProcessedAmountsVatBasesInner model = new ExpenseTempItemProcessedAmountsVatBasesInner();

    /**
     * Model tests for ExpenseTempItemProcessedAmountsVatBasesInner
     */
    @Test
    public void testExpenseTempItemProcessedAmountsVatBasesInner() {
        // TODO: test ExpenseTempItemProcessedAmountsVatBasesInner
    }

    /**
     * Test the property 'countryVatRateId'
     */
    @Test
    public void countryVatRateIdTest() {
        // TODO: test countryVatRateId
    }

    /**
     * Test the property 'countryVatRate'
     */
    @Test
    public void countryVatRateTest() {
        // TODO: test countryVatRate
    }

    /**
     * Test the property 'vatAmount'
     */
    @Test
    public void vatAmountTest() {
        // TODO: test vatAmount
    }

    /**
     * Test the property 'amountExcludingVat'
     */
    @Test
    public void amountExcludingVatTest() {
        // TODO: test amountExcludingVat
    }

}
