/*
 * Cleemy Expenses
 * Welcome on the documentation for the CleemyExpenses API. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developers@lucca.fr
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ExpenseClaimsCreateNewExpenseClaimResponseDataInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ExpenseClaimsCreateNewExpenseClaimResponse
 */
public class ExpenseClaimsCreateNewExpenseClaimResponseTest {
    private final ExpenseClaimsCreateNewExpenseClaimResponse model = new ExpenseClaimsCreateNewExpenseClaimResponse();

    /**
     * Model tests for ExpenseClaimsCreateNewExpenseClaimResponse
     */
    @Test
    public void testExpenseClaimsCreateNewExpenseClaimResponse() {
        // TODO: test ExpenseClaimsCreateNewExpenseClaimResponse
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

}
