/*
 * Cleemy Expenses
 * Welcome on the documentation for the CleemyExpenses API. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developers@lucca.fr
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ExpenseClaimsCreateNewExpenseClaimRequestInnerExpenseTempItemsInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ExpenseClaimsCreateNewExpenseClaimRequestInner
 */
public class ExpenseClaimsCreateNewExpenseClaimRequestInnerTest {
    private final ExpenseClaimsCreateNewExpenseClaimRequestInner model = new ExpenseClaimsCreateNewExpenseClaimRequestInner();

    /**
     * Model tests for ExpenseClaimsCreateNewExpenseClaimRequestInner
     */
    @Test
    public void testExpenseClaimsCreateNewExpenseClaimRequestInner() {
        // TODO: test ExpenseClaimsCreateNewExpenseClaimRequestInner
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'expenseTempItems'
     */
    @Test
    public void expenseTempItemsTest() {
        // TODO: test expenseTempItems
    }

}
