/*
 * Cleemy Expenses
 * Welcome on the documentation for the CleemyExpenses API. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developers@lucca.fr
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ExpenseTempItemProcessedAmountsVatBasesInnerCountryVatRate;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * ExpenseTempItemProcessedAmountsVatBasesInner
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ExpenseTempItemProcessedAmountsVatBasesInner {
  public static final String SERIALIZED_NAME_COUNTRY_VAT_RATE_ID = "countryVatRateId";
  @SerializedName(SERIALIZED_NAME_COUNTRY_VAT_RATE_ID)
  private Integer countryVatRateId;

  public static final String SERIALIZED_NAME_COUNTRY_VAT_RATE = "countryVatRate";
  @SerializedName(SERIALIZED_NAME_COUNTRY_VAT_RATE)
  private ExpenseTempItemProcessedAmountsVatBasesInnerCountryVatRate countryVatRate;

  public static final String SERIALIZED_NAME_VAT_AMOUNT = "vatAmount";
  @SerializedName(SERIALIZED_NAME_VAT_AMOUNT)
  private Double vatAmount;

  public static final String SERIALIZED_NAME_AMOUNT_EXCLUDING_VAT = "amountExcludingVat";
  @SerializedName(SERIALIZED_NAME_AMOUNT_EXCLUDING_VAT)
  private Double amountExcludingVat;

  public ExpenseTempItemProcessedAmountsVatBasesInner() {
  }

  public ExpenseTempItemProcessedAmountsVatBasesInner countryVatRateId(Integer countryVatRateId) {
    if (countryVatRateId != null && countryVatRateId < 1) {
      throw new IllegalArgumentException("Invalid value for countryVatRateId. Must be greater than or equal to 1.");
    }
    
    
    
    this.countryVatRateId = countryVatRateId;
    return this;
  }

   /**
   * Get countryVatRateId
   * minimum: 1
   * @return countryVatRateId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getCountryVatRateId() {
    return countryVatRateId;
  }


  public void setCountryVatRateId(Integer countryVatRateId) {
    if (countryVatRateId != null && countryVatRateId < 1) {
      throw new IllegalArgumentException("Invalid value for countryVatRateId. Must be greater than or equal to 1.");
    }
    
    
    this.countryVatRateId = countryVatRateId;
  }


  public ExpenseTempItemProcessedAmountsVatBasesInner countryVatRate(ExpenseTempItemProcessedAmountsVatBasesInnerCountryVatRate countryVatRate) {
    
    
    
    
    this.countryVatRate = countryVatRate;
    return this;
  }

   /**
   * Get countryVatRate
   * @return countryVatRate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ExpenseTempItemProcessedAmountsVatBasesInnerCountryVatRate getCountryVatRate() {
    return countryVatRate;
  }


  public void setCountryVatRate(ExpenseTempItemProcessedAmountsVatBasesInnerCountryVatRate countryVatRate) {
    
    
    
    this.countryVatRate = countryVatRate;
  }


  public ExpenseTempItemProcessedAmountsVatBasesInner vatAmount(Double vatAmount) {
    
    
    
    
    this.vatAmount = vatAmount;
    return this;
  }

  public ExpenseTempItemProcessedAmountsVatBasesInner vatAmount(Integer vatAmount) {
    
    
    
    
    this.vatAmount = vatAmount.doubleValue();
    return this;
  }

   /**
   * Get vatAmount
   * @return vatAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getVatAmount() {
    return vatAmount;
  }


  public void setVatAmount(Double vatAmount) {
    
    
    
    this.vatAmount = vatAmount;
  }


  public ExpenseTempItemProcessedAmountsVatBasesInner amountExcludingVat(Double amountExcludingVat) {
    
    
    
    
    this.amountExcludingVat = amountExcludingVat;
    return this;
  }

  public ExpenseTempItemProcessedAmountsVatBasesInner amountExcludingVat(Integer amountExcludingVat) {
    
    
    
    
    this.amountExcludingVat = amountExcludingVat.doubleValue();
    return this;
  }

   /**
   * Get amountExcludingVat
   * @return amountExcludingVat
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getAmountExcludingVat() {
    return amountExcludingVat;
  }


  public void setAmountExcludingVat(Double amountExcludingVat) {
    
    
    
    this.amountExcludingVat = amountExcludingVat;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ExpenseTempItemProcessedAmountsVatBasesInner instance itself
   */
  public ExpenseTempItemProcessedAmountsVatBasesInner putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExpenseTempItemProcessedAmountsVatBasesInner expenseTempItemProcessedAmountsVatBasesInner = (ExpenseTempItemProcessedAmountsVatBasesInner) o;
    return Objects.equals(this.countryVatRateId, expenseTempItemProcessedAmountsVatBasesInner.countryVatRateId) &&
        Objects.equals(this.countryVatRate, expenseTempItemProcessedAmountsVatBasesInner.countryVatRate) &&
        Objects.equals(this.vatAmount, expenseTempItemProcessedAmountsVatBasesInner.vatAmount) &&
        Objects.equals(this.amountExcludingVat, expenseTempItemProcessedAmountsVatBasesInner.amountExcludingVat)&&
        Objects.equals(this.additionalProperties, expenseTempItemProcessedAmountsVatBasesInner.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(countryVatRateId, countryVatRate, vatAmount, amountExcludingVat, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExpenseTempItemProcessedAmountsVatBasesInner {\n");
    sb.append("    countryVatRateId: ").append(toIndentedString(countryVatRateId)).append("\n");
    sb.append("    countryVatRate: ").append(toIndentedString(countryVatRate)).append("\n");
    sb.append("    vatAmount: ").append(toIndentedString(vatAmount)).append("\n");
    sb.append("    amountExcludingVat: ").append(toIndentedString(amountExcludingVat)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("countryVatRateId");
    openapiFields.add("countryVatRate");
    openapiFields.add("vatAmount");
    openapiFields.add("amountExcludingVat");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ExpenseTempItemProcessedAmountsVatBasesInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ExpenseTempItemProcessedAmountsVatBasesInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ExpenseTempItemProcessedAmountsVatBasesInner is not found in the empty JSON string", ExpenseTempItemProcessedAmountsVatBasesInner.openapiRequiredFields.toString()));
        }
      }
      // validate the optional field `countryVatRate`
      if (jsonObj.get("countryVatRate") != null && !jsonObj.get("countryVatRate").isJsonNull()) {
        ExpenseTempItemProcessedAmountsVatBasesInnerCountryVatRate.validateJsonObject(jsonObj.getAsJsonObject("countryVatRate"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ExpenseTempItemProcessedAmountsVatBasesInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ExpenseTempItemProcessedAmountsVatBasesInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ExpenseTempItemProcessedAmountsVatBasesInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ExpenseTempItemProcessedAmountsVatBasesInner.class));

       return (TypeAdapter<T>) new TypeAdapter<ExpenseTempItemProcessedAmountsVatBasesInner>() {
           @Override
           public void write(JsonWriter out, ExpenseTempItemProcessedAmountsVatBasesInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ExpenseTempItemProcessedAmountsVatBasesInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ExpenseTempItemProcessedAmountsVatBasesInner instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ExpenseTempItemProcessedAmountsVatBasesInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ExpenseTempItemProcessedAmountsVatBasesInner
  * @throws IOException if the JSON string is invalid with respect to ExpenseTempItemProcessedAmountsVatBasesInner
  */
  public static ExpenseTempItemProcessedAmountsVatBasesInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ExpenseTempItemProcessedAmountsVatBasesInner.class);
  }

 /**
  * Convert an instance of ExpenseTempItemProcessedAmountsVatBasesInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

