/*
 * Cleemy Expenses
 * Welcome on the documentation for the CleemyExpenses API. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developers@lucca.fr
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Authorized actions on the expenseClaim for the current user.
 */
@ApiModel(description = "Authorized actions on the expenseClaim for the current user.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ExpenseClaimAuthorizedActions {
  public static final String SERIALIZED_NAME_IS_CANCELLABLE = "isCancellable";
  @SerializedName(SERIALIZED_NAME_IS_CANCELLABLE)
  private Boolean isCancellable;

  public static final String SERIALIZED_NAME_IS_EDITABLE = "isEditable";
  @SerializedName(SERIALIZED_NAME_IS_EDITABLE)
  private Boolean isEditable;

  public static final String SERIALIZED_NAME_IS_APPROVABLE = "isApprovable";
  @SerializedName(SERIALIZED_NAME_IS_APPROVABLE)
  private Boolean isApprovable;

  public static final String SERIALIZED_NAME_IS_CONTROLLABLE = "isControllable";
  @SerializedName(SERIALIZED_NAME_IS_CONTROLLABLE)
  private Boolean isControllable;

  public static final String SERIALIZED_NAME_IS_UN_CONTROLLABLE = "isUnControllable";
  @SerializedName(SERIALIZED_NAME_IS_UN_CONTROLLABLE)
  private Boolean isUnControllable;

  public ExpenseClaimAuthorizedActions() {
  }

  public ExpenseClaimAuthorizedActions isCancellable(Boolean isCancellable) {
    
    
    
    
    this.isCancellable = isCancellable;
    return this;
  }

   /**
   * The expenseClaim can be deleted by the current authenticated user.
   * @return isCancellable
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The expenseClaim can be deleted by the current authenticated user.")

  public Boolean getIsCancellable() {
    return isCancellable;
  }


  public void setIsCancellable(Boolean isCancellable) {
    
    
    
    this.isCancellable = isCancellable;
  }


  public ExpenseClaimAuthorizedActions isEditable(Boolean isEditable) {
    
    
    
    
    this.isEditable = isEditable;
    return this;
  }

   /**
   * The expenseClaim can be edited by the current authenticated user.
   * @return isEditable
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The expenseClaim can be edited by the current authenticated user.")

  public Boolean getIsEditable() {
    return isEditable;
  }


  public void setIsEditable(Boolean isEditable) {
    
    
    
    this.isEditable = isEditable;
  }


  public ExpenseClaimAuthorizedActions isApprovable(Boolean isApprovable) {
    
    
    
    
    this.isApprovable = isApprovable;
    return this;
  }

   /**
   * The expenseClaim can be approved by the current authenticated user.
   * @return isApprovable
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The expenseClaim can be approved by the current authenticated user.")

  public Boolean getIsApprovable() {
    return isApprovable;
  }


  public void setIsApprovable(Boolean isApprovable) {
    
    
    
    this.isApprovable = isApprovable;
  }


  public ExpenseClaimAuthorizedActions isControllable(Boolean isControllable) {
    
    
    
    
    this.isControllable = isControllable;
    return this;
  }

   /**
   * The expenseClaim can be controlled by the current authenticated user.
   * @return isControllable
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The expenseClaim can be controlled by the current authenticated user.")

  public Boolean getIsControllable() {
    return isControllable;
  }


  public void setIsControllable(Boolean isControllable) {
    
    
    
    this.isControllable = isControllable;
  }


  public ExpenseClaimAuthorizedActions isUnControllable(Boolean isUnControllable) {
    
    
    
    
    this.isUnControllable = isUnControllable;
    return this;
  }

   /**
   * The current authenticated user can cancel the control of the expenseClaim.
   * @return isUnControllable
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The current authenticated user can cancel the control of the expenseClaim.")

  public Boolean getIsUnControllable() {
    return isUnControllable;
  }


  public void setIsUnControllable(Boolean isUnControllable) {
    
    
    
    this.isUnControllable = isUnControllable;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ExpenseClaimAuthorizedActions instance itself
   */
  public ExpenseClaimAuthorizedActions putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExpenseClaimAuthorizedActions expenseClaimAuthorizedActions = (ExpenseClaimAuthorizedActions) o;
    return Objects.equals(this.isCancellable, expenseClaimAuthorizedActions.isCancellable) &&
        Objects.equals(this.isEditable, expenseClaimAuthorizedActions.isEditable) &&
        Objects.equals(this.isApprovable, expenseClaimAuthorizedActions.isApprovable) &&
        Objects.equals(this.isControllable, expenseClaimAuthorizedActions.isControllable) &&
        Objects.equals(this.isUnControllable, expenseClaimAuthorizedActions.isUnControllable)&&
        Objects.equals(this.additionalProperties, expenseClaimAuthorizedActions.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isCancellable, isEditable, isApprovable, isControllable, isUnControllable, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExpenseClaimAuthorizedActions {\n");
    sb.append("    isCancellable: ").append(toIndentedString(isCancellable)).append("\n");
    sb.append("    isEditable: ").append(toIndentedString(isEditable)).append("\n");
    sb.append("    isApprovable: ").append(toIndentedString(isApprovable)).append("\n");
    sb.append("    isControllable: ").append(toIndentedString(isControllable)).append("\n");
    sb.append("    isUnControllable: ").append(toIndentedString(isUnControllable)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("isCancellable");
    openapiFields.add("isEditable");
    openapiFields.add("isApprovable");
    openapiFields.add("isControllable");
    openapiFields.add("isUnControllable");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ExpenseClaimAuthorizedActions
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ExpenseClaimAuthorizedActions.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ExpenseClaimAuthorizedActions is not found in the empty JSON string", ExpenseClaimAuthorizedActions.openapiRequiredFields.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ExpenseClaimAuthorizedActions.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ExpenseClaimAuthorizedActions' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ExpenseClaimAuthorizedActions> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ExpenseClaimAuthorizedActions.class));

       return (TypeAdapter<T>) new TypeAdapter<ExpenseClaimAuthorizedActions>() {
           @Override
           public void write(JsonWriter out, ExpenseClaimAuthorizedActions value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ExpenseClaimAuthorizedActions read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ExpenseClaimAuthorizedActions instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ExpenseClaimAuthorizedActions given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ExpenseClaimAuthorizedActions
  * @throws IOException if the JSON string is invalid with respect to ExpenseClaimAuthorizedActions
  */
  public static ExpenseClaimAuthorizedActions fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ExpenseClaimAuthorizedActions.class);
  }

 /**
  * Convert an instance of ExpenseClaimAuthorizedActions to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

