/*
 * Cleemy Expenses
 * Welcome on the documentation for the CleemyExpenses API. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developers@lucca.fr
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Additional information when the expense type is mileage.
 */
@ApiModel(description = "Additional information when the expense type is mileage.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ExpenseTempItemMileage {
  public static final String SERIALIZED_NAME_DISTANCE = "distance";
  @SerializedName(SERIALIZED_NAME_DISTANCE)
  private Double distance;

  public static final String SERIALIZED_NAME_POWER = "power";
  @SerializedName(SERIALIZED_NAME_POWER)
  private Double power;

  public static final String SERIALIZED_NAME_WAYPOINTS = "waypoints";
  @SerializedName(SERIALIZED_NAME_WAYPOINTS)
  private List<Object> waypoints = null;

  public ExpenseTempItemMileage() {
  }

  public ExpenseTempItemMileage distance(Double distance) {
    
    
    
    
    this.distance = distance;
    return this;
  }

  public ExpenseTempItemMileage distance(Integer distance) {
    
    
    
    
    this.distance = distance.doubleValue();
    return this;
  }

   /**
   * Distance where the unit depends on the establishment.
   * @return distance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Distance where the unit depends on the establishment.")

  public Double getDistance() {
    return distance;
  }


  public void setDistance(Double distance) {
    
    
    
    this.distance = distance;
  }


  public ExpenseTempItemMileage power(Double power) {
    
    
    
    
    this.power = power;
    return this;
  }

  public ExpenseTempItemMileage power(Integer power) {
    
    
    
    
    this.power = power.doubleValue();
    return this;
  }

   /**
   * Tax horsepower of the vehicle.
   * @return power
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Tax horsepower of the vehicle.")

  public Double getPower() {
    return power;
  }


  public void setPower(Double power) {
    
    
    
    this.power = power;
  }


  public ExpenseTempItemMileage waypoints(List<Object> waypoints) {
    
    
    
    
    this.waypoints = waypoints;
    return this;
  }

  public ExpenseTempItemMileage addWaypointsItem(Object waypointsItem) {
    if (this.waypoints == null) {
      this.waypoints = new ArrayList<>();
    }
    this.waypoints.add(waypointsItem);
    return this;
  }

   /**
   * The collection of waypoints including intermediate waypoints.
   * @return waypoints
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The collection of waypoints including intermediate waypoints.")

  public List<Object> getWaypoints() {
    return waypoints;
  }


  public void setWaypoints(List<Object> waypoints) {
    
    
    
    this.waypoints = waypoints;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ExpenseTempItemMileage instance itself
   */
  public ExpenseTempItemMileage putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExpenseTempItemMileage expenseTempItemMileage = (ExpenseTempItemMileage) o;
    return Objects.equals(this.distance, expenseTempItemMileage.distance) &&
        Objects.equals(this.power, expenseTempItemMileage.power) &&
        Objects.equals(this.waypoints, expenseTempItemMileage.waypoints)&&
        Objects.equals(this.additionalProperties, expenseTempItemMileage.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(distance, power, waypoints, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExpenseTempItemMileage {\n");
    sb.append("    distance: ").append(toIndentedString(distance)).append("\n");
    sb.append("    power: ").append(toIndentedString(power)).append("\n");
    sb.append("    waypoints: ").append(toIndentedString(waypoints)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("distance");
    openapiFields.add("power");
    openapiFields.add("waypoints");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ExpenseTempItemMileage
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ExpenseTempItemMileage.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ExpenseTempItemMileage is not found in the empty JSON string", ExpenseTempItemMileage.openapiRequiredFields.toString()));
        }
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("waypoints") != null && !jsonObj.get("waypoints").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `waypoints` to be an array in the JSON string but got `%s`", jsonObj.get("waypoints").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ExpenseTempItemMileage.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ExpenseTempItemMileage' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ExpenseTempItemMileage> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ExpenseTempItemMileage.class));

       return (TypeAdapter<T>) new TypeAdapter<ExpenseTempItemMileage>() {
           @Override
           public void write(JsonWriter out, ExpenseTempItemMileage value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ExpenseTempItemMileage read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ExpenseTempItemMileage instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ExpenseTempItemMileage given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ExpenseTempItemMileage
  * @throws IOException if the JSON string is invalid with respect to ExpenseTempItemMileage
  */
  public static ExpenseTempItemMileage fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ExpenseTempItemMileage.class);
  }

 /**
  * Convert an instance of ExpenseTempItemMileage to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

