/*
 * Cleemy Expenses
 * Welcome on the documentation for the CleemyExpenses API. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developers@lucca.fr
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Currency;
import com.konfigthis.client.model.ExpenseTempItemProcessedAmountsVatBasesInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Various amounts in the establishment&#39;s currency.
 */
@ApiModel(description = "Various amounts in the establishment's currency.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ExpenseTempItemProcessedAmounts {
  public static final String SERIALIZED_NAME_GROSS_AMOUNT = "grossAmount";
  @SerializedName(SERIALIZED_NAME_GROSS_AMOUNT)
  private Double grossAmount;

  public static final String SERIALIZED_NAME_CURRENCY_ID = "currencyId";
  @SerializedName(SERIALIZED_NAME_CURRENCY_ID)
  private String currencyId;

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  private Currency currency;

  public static final String SERIALIZED_NAME_NET_AMOUNT = "netAmount";
  @SerializedName(SERIALIZED_NAME_NET_AMOUNT)
  private Double netAmount;

  public static final String SERIALIZED_NAME_VAT_BASES = "vatBases";
  @SerializedName(SERIALIZED_NAME_VAT_BASES)
  private List<ExpenseTempItemProcessedAmountsVatBasesInner> vatBases = null;

  public ExpenseTempItemProcessedAmounts() {
  }

  public ExpenseTempItemProcessedAmounts grossAmount(Double grossAmount) {
    
    
    
    
    this.grossAmount = grossAmount;
    return this;
  }

  public ExpenseTempItemProcessedAmounts grossAmount(Integer grossAmount) {
    
    
    
    
    this.grossAmount = grossAmount.doubleValue();
    return this;
  }

   /**
   * Original transaction amount converted into the establishment&#39;s currency.
   * @return grossAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "57.9", value = "Original transaction amount converted into the establishment's currency.")

  public Double getGrossAmount() {
    return grossAmount;
  }


  public void setGrossAmount(Double grossAmount) {
    
    
    
    this.grossAmount = grossAmount;
  }


  public ExpenseTempItemProcessedAmounts currencyId(String currencyId) {
    
    
    
    
    this.currencyId = currencyId;
    return this;
  }

   /**
   * ISO code of the currency (eg: &#39;EUR&#39;, &#39;USD&#39;, &#39;GBP&#39;, ...).
   * @return currencyId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "GBP", value = "ISO code of the currency (eg: 'EUR', 'USD', 'GBP', ...).")

  public String getCurrencyId() {
    return currencyId;
  }


  public void setCurrencyId(String currencyId) {
    
    
    
    this.currencyId = currencyId;
  }


  public ExpenseTempItemProcessedAmounts currency(Currency currency) {
    
    
    
    
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Currency getCurrency() {
    return currency;
  }


  public void setCurrency(Currency currency) {
    
    
    
    this.currency = currency;
  }


  public ExpenseTempItemProcessedAmounts netAmount(Double netAmount) {
    
    
    
    
    this.netAmount = netAmount;
    return this;
  }

  public ExpenseTempItemProcessedAmounts netAmount(Integer netAmount) {
    
    
    
    
    this.netAmount = netAmount.doubleValue();
    return this;
  }

   /**
   * The converted amount after the expense policy has been applied.
   * @return netAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "57.9", value = "The converted amount after the expense policy has been applied.")

  public Double getNetAmount() {
    return netAmount;
  }


  public void setNetAmount(Double netAmount) {
    
    
    
    this.netAmount = netAmount;
  }


  public ExpenseTempItemProcessedAmounts vatBases(List<ExpenseTempItemProcessedAmountsVatBasesInner> vatBases) {
    
    
    
    
    this.vatBases = vatBases;
    return this;
  }

  public ExpenseTempItemProcessedAmounts addVatBasesItem(ExpenseTempItemProcessedAmountsVatBasesInner vatBasesItem) {
    if (this.vatBases == null) {
      this.vatBases = new ArrayList<>();
    }
    this.vatBases.add(vatBasesItem);
    return this;
  }

   /**
   * Get vatBases
   * @return vatBases
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<ExpenseTempItemProcessedAmountsVatBasesInner> getVatBases() {
    return vatBases;
  }


  public void setVatBases(List<ExpenseTempItemProcessedAmountsVatBasesInner> vatBases) {
    
    
    
    this.vatBases = vatBases;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ExpenseTempItemProcessedAmounts instance itself
   */
  public ExpenseTempItemProcessedAmounts putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExpenseTempItemProcessedAmounts expenseTempItemProcessedAmounts = (ExpenseTempItemProcessedAmounts) o;
    return Objects.equals(this.grossAmount, expenseTempItemProcessedAmounts.grossAmount) &&
        Objects.equals(this.currencyId, expenseTempItemProcessedAmounts.currencyId) &&
        Objects.equals(this.currency, expenseTempItemProcessedAmounts.currency) &&
        Objects.equals(this.netAmount, expenseTempItemProcessedAmounts.netAmount) &&
        Objects.equals(this.vatBases, expenseTempItemProcessedAmounts.vatBases)&&
        Objects.equals(this.additionalProperties, expenseTempItemProcessedAmounts.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(grossAmount, currencyId, currency, netAmount, vatBases, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExpenseTempItemProcessedAmounts {\n");
    sb.append("    grossAmount: ").append(toIndentedString(grossAmount)).append("\n");
    sb.append("    currencyId: ").append(toIndentedString(currencyId)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    netAmount: ").append(toIndentedString(netAmount)).append("\n");
    sb.append("    vatBases: ").append(toIndentedString(vatBases)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("grossAmount");
    openapiFields.add("currencyId");
    openapiFields.add("currency");
    openapiFields.add("netAmount");
    openapiFields.add("vatBases");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ExpenseTempItemProcessedAmounts
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ExpenseTempItemProcessedAmounts.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ExpenseTempItemProcessedAmounts is not found in the empty JSON string", ExpenseTempItemProcessedAmounts.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("currencyId") != null && !jsonObj.get("currencyId").isJsonNull()) && !jsonObj.get("currencyId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `currencyId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("currencyId").toString()));
      }
      // validate the optional field `currency`
      if (jsonObj.get("currency") != null && !jsonObj.get("currency").isJsonNull()) {
        Currency.validateJsonObject(jsonObj.getAsJsonObject("currency"));
      }
      if (jsonObj.get("vatBases") != null && !jsonObj.get("vatBases").isJsonNull()) {
        JsonArray jsonArrayvatBases = jsonObj.getAsJsonArray("vatBases");
        if (jsonArrayvatBases != null) {
          // ensure the json data is an array
          if (!jsonObj.get("vatBases").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `vatBases` to be an array in the JSON string but got `%s`", jsonObj.get("vatBases").toString()));
          }

          // validate the optional field `vatBases` (array)
          for (int i = 0; i < jsonArrayvatBases.size(); i++) {
            ExpenseTempItemProcessedAmountsVatBasesInner.validateJsonObject(jsonArrayvatBases.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ExpenseTempItemProcessedAmounts.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ExpenseTempItemProcessedAmounts' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ExpenseTempItemProcessedAmounts> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ExpenseTempItemProcessedAmounts.class));

       return (TypeAdapter<T>) new TypeAdapter<ExpenseTempItemProcessedAmounts>() {
           @Override
           public void write(JsonWriter out, ExpenseTempItemProcessedAmounts value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ExpenseTempItemProcessedAmounts read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ExpenseTempItemProcessedAmounts instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ExpenseTempItemProcessedAmounts given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ExpenseTempItemProcessedAmounts
  * @throws IOException if the JSON string is invalid with respect to ExpenseTempItemProcessedAmounts
  */
  public static ExpenseTempItemProcessedAmounts fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ExpenseTempItemProcessedAmounts.class);
  }

 /**
  * Convert an instance of ExpenseTempItemProcessedAmounts to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

