/*
 * Cleemy Expenses
 * Welcome on the documentation for the CleemyExpenses API. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: developers@lucca.fr
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ExpenseTempItemAttendeesExternalInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Additional information when the expense type is &#39;Invitation&#39;.
 */
@ApiModel(description = "Additional information when the expense type is 'Invitation'.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ExpenseTempItemAttendees {
  public static final String SERIALIZED_NAME_INTERNAL = "internal";
  @SerializedName(SERIALIZED_NAME_INTERNAL)
  private List<Object> internal = null;

  public static final String SERIALIZED_NAME_EXTERNAL = "external";
  @SerializedName(SERIALIZED_NAME_EXTERNAL)
  private List<ExpenseTempItemAttendeesExternalInner> external = null;

  public ExpenseTempItemAttendees() {
  }

  public ExpenseTempItemAttendees internal(List<Object> internal) {
    
    
    
    
    this.internal = internal;
    return this;
  }

  public ExpenseTempItemAttendees addInternalItem(Object internalItem) {
    if (this.internal == null) {
      this.internal = new ArrayList<>();
    }
    this.internal.add(internalItem);
    return this;
  }

   /**
   * Attendees who work for the company (ie: Users in the system).
   * @return internal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Attendees who work for the company (ie: Users in the system).")

  public List<Object> getInternal() {
    return internal;
  }


  public void setInternal(List<Object> internal) {
    
    
    
    this.internal = internal;
  }


  public ExpenseTempItemAttendees external(List<ExpenseTempItemAttendeesExternalInner> external) {
    
    
    
    
    this.external = external;
    return this;
  }

  public ExpenseTempItemAttendees addExternalItem(ExpenseTempItemAttendeesExternalInner externalItem) {
    if (this.external == null) {
      this.external = new ArrayList<>();
    }
    this.external.add(externalItem);
    return this;
  }

   /**
   * External attendees (eg: clients, candidates).
   * @return external
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "External attendees (eg: clients, candidates).")

  public List<ExpenseTempItemAttendeesExternalInner> getExternal() {
    return external;
  }


  public void setExternal(List<ExpenseTempItemAttendeesExternalInner> external) {
    
    
    
    this.external = external;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ExpenseTempItemAttendees instance itself
   */
  public ExpenseTempItemAttendees putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExpenseTempItemAttendees expenseTempItemAttendees = (ExpenseTempItemAttendees) o;
    return Objects.equals(this.internal, expenseTempItemAttendees.internal) &&
        Objects.equals(this.external, expenseTempItemAttendees.external)&&
        Objects.equals(this.additionalProperties, expenseTempItemAttendees.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(internal, external, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExpenseTempItemAttendees {\n");
    sb.append("    internal: ").append(toIndentedString(internal)).append("\n");
    sb.append("    external: ").append(toIndentedString(external)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("internal");
    openapiFields.add("external");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ExpenseTempItemAttendees
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ExpenseTempItemAttendees.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ExpenseTempItemAttendees is not found in the empty JSON string", ExpenseTempItemAttendees.openapiRequiredFields.toString()));
        }
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("internal") != null && !jsonObj.get("internal").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `internal` to be an array in the JSON string but got `%s`", jsonObj.get("internal").toString()));
      }
      if (jsonObj.get("external") != null && !jsonObj.get("external").isJsonNull()) {
        JsonArray jsonArrayexternal = jsonObj.getAsJsonArray("external");
        if (jsonArrayexternal != null) {
          // ensure the json data is an array
          if (!jsonObj.get("external").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `external` to be an array in the JSON string but got `%s`", jsonObj.get("external").toString()));
          }

          // validate the optional field `external` (array)
          for (int i = 0; i < jsonArrayexternal.size(); i++) {
            ExpenseTempItemAttendeesExternalInner.validateJsonObject(jsonArrayexternal.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ExpenseTempItemAttendees.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ExpenseTempItemAttendees' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ExpenseTempItemAttendees> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ExpenseTempItemAttendees.class));

       return (TypeAdapter<T>) new TypeAdapter<ExpenseTempItemAttendees>() {
           @Override
           public void write(JsonWriter out, ExpenseTempItemAttendees value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ExpenseTempItemAttendees read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ExpenseTempItemAttendees instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ExpenseTempItemAttendees given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ExpenseTempItemAttendees
  * @throws IOException if the JSON string is invalid with respect to ExpenseTempItemAttendees
  */
  public static ExpenseTempItemAttendees fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ExpenseTempItemAttendees.class);
  }

 /**
  * Convert an instance of ExpenseTempItemAttendees to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

